Repository Kernel360/KBE5-CleanPick-BE, pull requests merged in 2025-05, with the labels that each got.

#9 feat: 리뷰 관련 기능 개발(작성/조회) #3
  src/main/java/com/kdev5/cleanpick/contract/domain/exception/ContractNotFoundException.java
  src/main/java/com/kdev5/cleanpick/customer/domain/Customer.java
  src/main/java/com/kdev5/cleanpick/global/exception/ErrorCode.java
  src/main/java/com/kdev5/cleanpick/global/exception/GlobalExceptionHandler.java
  src/main/java/com/kdev5/cleanpick/global/response/PageResponse.java
  src/main/java/com/kdev5/cleanpick/manager/domain/Manager.java
  src/main/java/com/kdev5/cleanpick/manager/infra/repository/ManagerRepository.java
  src/main/java/com/kdev5/cleanpick/review/Infra/ReviewFileRepository.java
  src/main/java/com/kdev5/cleanpick/review/Infra/ReviewImageRepository.java
  src/main/java/com/kdev5/cleanpick/review/Infra/ReviewRepository.java
  src/main/java/com/kdev5/cleanpick/review/controller/ReviewController.java
  src/main/java/com/kdev5/cleanpick/review/domain/Review.java
  src/main/java/com/kdev5/cleanpick/review/domain/exception/ReviewDuplicateException.java
  src/main/java/com/kdev5/cleanpick/review/service/ReviewService.java
  src/main/java/com/kdev5/cleanpick/review/service/dto/request/WriteReviewRequestDto.java
  src/main/java/com/kdev5/cleanpick/review/service/dto/response/ReviewResponseDto.java
Labels: enhancement

#19 feat: 예약 관련 상세/목록 조회 개발 기능
  src/main/java/com/kdev5/cleanpick/cleaning/domain/Cleaning.java
  src/main/java/com/kdev5/cleanpick/cleaning/domain/CleaningOption.java
  src/main/java/com/kdev5/cleanpick/common/util/DateTimeUtil.java
  src/main/java/com/kdev5/cleanpick/contract/controller/ContractController.java
  src/main/java/com/kdev5/cleanpick/contract/domain/Contract.java
  src/main/java/com/kdev5/cleanpick/contract/domain/ContractDetail.java
  src/main/java/com/kdev5/cleanpick/contract/domain/ContractOption.java
  src/main/java/com/kdev5/cleanpick/contract/domain/exception/ContractException.java
  src/main/java/com/kdev5/cleanpick/contract/dto/ContractRequestDto.java
  src/main/java/com/kdev5/cleanpick/contract/infra/ContractDetailRepository.java
  src/main/java/com/kdev5/cleanpick/contract/infra/ContractOptionRepository.java
  src/main/java/com/kdev5/cleanpick/contract/infra/ContractRepository.java
  src/main/java/com/kdev5/cleanpick/contract/infra/querydsl/ContractDetailRepositoryCustom.java
  src/main/java/com/kdev5/cleanpick/contract/infra/querydsl/ContractDetailRepositoryImpl.java
  src/main/java/com/kdev5/cleanpick/contract/infra/querydsl/ContractOptionRepositoryCustom.java
  src/main/java/com/kdev5/cleanpick/contract/infra/querydsl/ContractOptionRepositoryImpl.java
  src/main/java/com/kdev5/cleanpick/contract/infra/querydsl/ContractRepositoryCustom.java
  src/main/java/com/kdev5/cleanpick/contract/infra/querydsl/ContractRepositoryImpl.java
  src/main/java/com/kdev5/cleanpick/contract/service/ContractServiceImpl.java
  src/main/java/com/kdev5/cleanpick/contract/service/ReadContractService.java
  src/main/java/com/kdev5/cleanpick/contract/service/dto/request/ContractFilterStatus.java
  src/main/java/com/kdev5/cleanpick/contract/service/dto/response/ReadContractDetailResponseDto.java
  src/main/java/com/kdev5/cleanpick/contract/service/dto/response/ReadContractOptionResponseDto.java
  src/main/java/com/kdev5/cleanpick/contract/service/dto/response/ReadContractResponseDto.java
  src/main/java/com/kdev5/cleanpick/review/service/ReviewService.java
  src/test/java/com/kdev5/cleanpick/contract/service/ReadContractServiceTest.java
Labels: enhancement

#27 Feature/18
  .gitignore
  src/main/java/com/kdev5/cleanpick/customer/controller/CustomerController.java
  src/main/java/com/kdev5/cleanpick/customer/domain/Customer.java
  src/main/java/com/kdev5/cleanpick/customer/service/CustomerService.java
  src/main/java/com/kdev5/cleanpick/customer/service/dto/response/CustomerResponseDto.java
  src/main/java/com/kdev5/cleanpick/global/security/auth/CustomUserDetails.java
  src/main/java/com/kdev5/cleanpick/global/security/filter/JwtLoginAuthenticationFilter.java
  src/main/java/com/kdev5/cleanpick/global/security/jwt/JwtProcessor.java
  src/main/java/com/kdev5/cleanpick/manager/domain/Manager.java
  src/main/java/com/kdev5/cleanpick/user/controller/UserController.java
  src/main/java/com/kdev5/cleanpick/user/domain/Status.java
  src/main/java/com/kdev5/cleanpick/user/domain/User.java
  src/main/java/com/kdev5/cleanpick/user/service/UserService.java
  src/main/java/com/kdev5/cleanpick/user/service/dto/request/SignUpRequestDto.java
  src/main/java/com/kdev5/cleanpick/user/service/dto/response/UserResponseDto.java
Labels: ✨ Feature, 🔧 Refactor

#30 Feature/3
  src/main/java/com/kdev5/cleanpick/review/Infra/ReviewRepository.java
  src/main/java/com/kdev5/cleanpick/review/controller/ReviewController.java
  src/main/java/com/kdev5/cleanpick/review/domain/Review.java
  src/main/java/com/kdev5/cleanpick/review/domain/ReviewFile.java
  src/main/java/com/kdev5/cleanpick/review/service/ReviewService.java
  src/test/java/com/kdev5/cleanpick/contract/service/ReadContractServiceTest.java
  src/test/java/com/kdev5/cleanpick/review/service/ReviewServiceTest.java
Labels: ✨ Feature

#32 Feature/31
  src/main/java/com/kdev5/cleanpick/contract/controller/MatchingController.java
  src/main/java/com/kdev5/cleanpick/contract/domain/Contract.java
  src/main/java/com/kdev5/cleanpick/contract/domain/Nominee.java
  src/main/java/com/kdev5/cleanpick/contract/domain/enumeration/MatchingStatus.java
  src/main/java/com/kdev5/cleanpick/contract/domain/exception/NomineeException.java
  src/main/java/com/kdev5/cleanpick/contract/infra/NomineeRepository.java
  src/main/java/com/kdev5/cleanpick/contract/service/ContractMatchingService.java
  src/main/java/com/kdev5/cleanpick/global/exception/ErrorCode.java
  src/main/java/com/kdev5/cleanpick/global/response/ApiResponse.java
  src/test/java/com/kdev5/cleanpick/contract/service/ContractMatchingServiceTest.java
Labels: ✨ Feature

#33 Refactor/4
  .gitignore
  src/main/java/com/kdev5/cleanpick/manager/controller/ManagerController.java
  src/main/java/com/kdev5/cleanpick/manager/domain/enumeration/SortType.java
  src/main/java/com/kdev5/cleanpick/manager/infra/querydsl/ManagerAvailableCleaningRepositoryCustom.java
  src/main/java/com/kdev5/cleanpick/manager/infra/querydsl/ManagerAvailableCleaningRepositoryImpl.java
  src/main/java/com/kdev5/cleanpick/manager/infra/querydsl/ManagerAvailableRegionRepositoryCustom.java
  src/main/java/com/kdev5/cleanpick/manager/infra/querydsl/ManagerAvailableRegionRepositoryImpl.java
  src/main/java/com/kdev5/cleanpick/manager/infra/querydsl/ManagerRepositoryCustom.java
  src/main/java/com/kdev5/cleanpick/manager/infra/querydsl/ManagerRepositoryImpl.java
  src/main/java/com/kdev5/cleanpick/manager/infra/repository/ManagerAvailableCleaningRepository.java
  src/main/java/com/kdev5/cleanpick/manager/infra/repository/ManagerAvailableRegionRepository.java
  src/main/java/com/kdev5/cleanpick/manager/infra/repository/ManagerRepository.java
  src/main/java/com/kdev5/cleanpick/manager/service/ManagerService.java
  src/main/java/com/kdev5/cleanpick/manager/service/dto/response/ManagerSearchResponseDto.java
  src/main/java/com/kdev5/cleanpick/review/Infra/ReviewRepository.java
  src/main/java/com/kdev5/cleanpick/review/Infra/querydsl/ReviewRepositoryCustom.java
  src/main/java/com/kdev5/cleanpick/review/Infra/querydsl/ReviewRepositoryImpl.java
Labels: 🔧 Refactor

#36 Feature/18
  build.gradle
  src/main/java/com/kdev5/cleanpick/common/file/FileUtils.java
  src/main/java/com/kdev5/cleanpick/common/file/PreSignedUrlController.java
  src/main/java/com/kdev5/cleanpick/common/file/PreSignedUrlService.java
  src/main/java/com/kdev5/cleanpick/common/file/dto/PreSignedUrlRequest.java
  src/main/java/com/kdev5/cleanpick/common/file/dto/PreSignedUrlResponse.java
  src/main/java/com/kdev5/cleanpick/common/file/exception/FileTypeException.java
  src/main/java/com/kdev5/cleanpick/customer/controller/CustomerController.java
  src/main/java/com/kdev5/cleanpick/customer/domain/Customer.java
  src/main/java/com/kdev5/cleanpick/customer/service/CustomerService.java
  src/main/java/com/kdev5/cleanpick/customer/service/dto/request/WriteCustomerRequestDto.java
  src/main/java/com/kdev5/cleanpick/customer/service/dto/response/CustomerPrivateResponseDto.java
  src/main/java/com/kdev5/cleanpick/customer/service/dto/response/CustomerResponseDto.java
  src/main/java/com/kdev5/cleanpick/global/config/S3Config.java
  src/main/java/com/kdev5/cleanpick/global/config/WebConfig.java
  src/main/java/com/kdev5/cleanpick/global/exception/ErrorCode.java
  src/main/java/com/kdev5/cleanpick/global/security/config/SecurityConfig.java
  src/main/java/com/kdev5/cleanpick/user/domain/User.java
  src/main/java/com/kdev5/cleanpick/user/domain/exception/UserNotFoundException.java
  src/test/java/com/kdev5/cleanpick/common/file/FileUtilsTest.java
Labels: ✨ Feature

#35 Feature/26
  src/main/java/com/kdev5/cleanpick/contract/controller/ContractController.java
  src/main/java/com/kdev5/cleanpick/contract/domain/Contract.java
  src/main/java/com/kdev5/cleanpick/contract/domain/ContractDetail.java
  src/main/java/com/kdev5/cleanpick/contract/domain/ContractOption.java
  src/main/java/com/kdev5/cleanpick/contract/domain/Nominee.java
  src/main/java/com/kdev5/cleanpick/contract/domain/RoutineContract.java
  src/main/java/com/kdev5/cleanpick/contract/infra/ContractRepository.java
  src/main/java/com/kdev5/cleanpick/contract/service/ContractService.java
  src/main/java/com/kdev5/cleanpick/contract/service/ContractServiceImpl.java
  src/main/java/com/kdev5/cleanpick/contract/service/dto/request/UpdateContractRequestDto.java
  src/main/java/com/kdev5/cleanpick/global/entity/BaseTimeEntity.java
  src/main/java/com/kdev5/cleanpick/global/exception/ErrorCode.java
  src/main/java/com/kdev5/cleanpick/manager/domain/ManagerAvailableTime.java
  src/main/java/com/kdev5/cleanpick/manager/domain/exception/ManagerNotAvailableTimeException.java
  src/main/java/com/kdev5/cleanpick/manager/infra/repository/ManagerAvailableTimeRepository.java
Labels: ✨ Feature
