Repository Kernel360/KBE5-CleanPick-BE, pull requests merged in 2025-06, with the labels that each got.

#40 Feature/38
  src/main/java/com/kdev5/cleanpick/common/file/PreSignedUrlService.java
  src/main/java/com/kdev5/cleanpick/contract/controller/RevenueController.java
  src/main/java/com/kdev5/cleanpick/contract/domain/Contract.java
  src/main/java/com/kdev5/cleanpick/contract/infra/querydsl/ContractRepositoryCustom.java
  src/main/java/com/kdev5/cleanpick/contract/infra/querydsl/ContractRepositoryImpl.java
  src/main/java/com/kdev5/cleanpick/contract/service/RevenueService.java
  src/main/java/com/kdev5/cleanpick/contract/service/dto/response/ReadMonthlyRevenueResponseDto.java
  src/main/java/com/kdev5/cleanpick/contract/service/dto/response/ReadWorkHistoryResponseDto.java
  src/main/java/com/kdev5/cleanpick/manager/infra/querydsl/ManagerAvailableCleaningRepositoryImpl.java
  src/main/java/com/kdev5/cleanpick/manager/infra/querydsl/ManagerRepositoryImpl.java
Labels: ✨ Feature

#49 ci/cd: 헬스체크 위한 actuator 의존성 추가
  build.gradle
Labels: 🤖 CI/CD

#55 Feature/54
  package-lock.json
  package.json
  src/main/java/com/kdev5/cleanpick/customer/service/dto/response/CustomerPrivateResponseDto.java
  src/main/java/com/kdev5/cleanpick/manager/domain/Manager.java
  src/main/java/com/kdev5/cleanpick/manager/domain/ManagerAvailableTime.java
  src/main/java/com/kdev5/cleanpick/manager/domain/enumeration/DayOfWeek.java
  src/main/java/com/kdev5/cleanpick/manager/service/dto/AvailableTimeDto.java
  src/main/java/com/kdev5/cleanpick/manager/service/dto/request/ManagerDetailRequestDto.java
  src/main/java/com/kdev5/cleanpick/user/domain/User.java
  src/test/java/com/kdev5/cleanpick/common/file/FileUtilsTest.java
  src/test/java/com/kdev5/cleanpick/customer/controller/CustomerControllerTest.java
  src/test/java/com/kdev5/cleanpick/customer/service/CustomerServiceTest.java
  src/test/java/com/kdev5/cleanpick/global/security/AuthIntegrationTest.java
  src/test/java/com/kdev5/cleanpick/manager/controller/ManagerControllerTest.java
Labels: 🔧 Refactor
